FROM node:12.16.3

RUN apt-get update && apt-get upgrade -y

WORKDIR /app

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

CMD /wait && yarn run migration-dev && yarn run dev
